const products = [
    {
      _id: "1",
      name: "Product 1",
      image: "/images/airpods.jpg",
      description: "This is the description for Product 1",
      brand: "Brand A",
      category: "Category A",
      price: 29.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: "2",
      name: "Product 2",
      image: "/images/alexa.jpg",
      description: "This is the description for Product 2",
      brand: "Brand B",
      category: "Category B",
      price: 59.99,
      countInStock: 7,
      rating: 4.0,
      numReviews: 8,
    },
    {
      _id: "3",
      name: "Product 3",
      image: "/images/camera.jpg",
      description: "This is the description for Product 3",
      brand: "Brand C",
      category: "Category C",
      price: 19.99,
      countInStock: 5,
      rating: 3.5,
      numReviews: 5,
    },
    {
      _id: "4",
      name: "Product 4",
      image: "/images/mouse.jpg",
      description: "This is the description for Product 4",
      brand: "Brand D",
      category: "Category D",
      price: 99.99,
      countInStock: 2,
      rating: 5.0,
      numReviews: 20,
    },
    {
      _id: "5",
      name: "Product 5",
      image: "/images/phone.jpg",
      description: "This is the description for Product 5",
      brand: "Brand E",
      category: "Category E",
      price: 39.99,
      countInStock: 0,
      rating: 4.8,
      numReviews: 25,
    },
    {
        _id: "6",
        name: "Product 6",
        image: "/images/playstation.jpg",
        description: "This is the description for Product 5",
        brand: "Brand E",
        category: "Category E",
        price: 39.99,
        countInStock: 0,
        rating: 4.8,
        numReviews: 25,
      },
   
  ];
  
  export default products;
  